eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url.defaultZone: "http://localhost:7001/eureka/"
  instance:
    appname: pro
server:
  port: 80

spring:
  application:
    name: provider
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

